### ISSUE TITLE
Make How-To Contribute

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI-Community/ACCESSHub#1]
As a user who wishes to contribute I need guidelines on how to do this. Without the guidelines I would be worried I was doing the wrong thing, and this would make me less likely to contribute.

**Comment by aidanheerdegen** [comment]
@ccarouge do you have time to do this today? If so, I can review the PR by doing #8 and provide feedback.

**Comment by ccarouge** [comment]
I'm working on it right now.
